using System.Diagnostics.CodeAnalysis;
using Embedded;

[SuppressMessage("ReSharper", "UnassignedReadonlyField")]
public static class Defaults
{
    // TODO: implement ExternalLiteral in Embedded.Fody

    // see Defaults/GameSettings
    [Base64Literal(0,
        @"AQEBAQEBAQEBAQEBAACAPwAAgD8MAQIDBAUGBwkKCwwNAAAAgD8AAIA/AAAAPwAAAD8BBQAAAAEAAAAAAAEAAAD/////////" +
        @"//////8AAAEBAQAAAEoARQBuAHYAaQByAG8AbgBtAGUAbgB0AC8ARQB2AGUAbgB0AHMALwBMAGEAcgBnAGUALwBtAGkAbABp" +
        @"AHQAYQByAHkAcwBoAGkAcAACAAAAAAEBAQAAAAA/AAAAAC4ATgBWAEkARABJAEEAIABHAGUARgBvAHIAYwBlACAAUgBUAFgA" +
        @"IAAzADAAOQAwAAAPAABwCAAAHAAAAGDqAADoAwAAARcAAAAAAAAAAAIAAwAAAgICAgICAgIAAAAAwD8BAQABAgEAAAEAAAAA" +
        @"AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A" +
        @"AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A" +
        @"AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A" +
        @"AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A" +
        @"AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A" +
        @"AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A" +
        @"AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A" +
        @"AIA/AACAPwAAgD8DAQEAAAAAAAABmpmZPgEBAAAgQgAAIEEAAKBAAAAAPwAAAD/NzEw/mpkZPs3MTD3NzMw9zczMPc3MzD0A" +
        @"AIA/AACAP/kClU8oa25OwOHkTCC8PkwAAIA/AACAPwAAgD8AAIA/AACAPwEB7FE4Po/CdT7NzEw+mpkZPilcjz0K16M9Ctej" +
        @"PQABARwAAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAADMzsz4AAAA/mpkZPgAAAAABzcxMPs3MTD97FK4+AACA" +
        @"PwAAgD8BAQEBAQEBAQEBcAAAABIAAAAAAHgAAFUAAAAAAHkAAFcAAAAAAHoAACwAAAAAAHwAAS8AAAAAAH0AAUIAAAAAAH4A" +
        @"AT4AAAAAAH8AATwAAAAAAJUAATAAAAAAAJYAATwAAAABAJMAADAAAAABAJQAAAMAAAABAIQAADcAAAAAAGQAAI4AAAAAAIMA" +
        @"AJAAAAAAAIIAAC0AAAAAAIgAAD8AAAAAAIkAADIAAAABAIoAADIAAAAAAIsAAD8AAAABAIwAAC0AAAABAI0AAAIAAAAAAGcA" +
        @"ABQAAAAAAGUAARMAAAAAAGYAARYAAAAAAGgAABUAAAAAAGkAAB8AAAAAAGoAACAAAAAAAGsAAFoAAAAAQQAAAEEAAAAACAAA" +
        @"AAAAAAAAQAAAAJEAAAAAPgAAAAAAAAAAPwAAAJgAAAABQwAAAIwAAAABRAAAAD0AAAAAAFAAAI0AAAAAAAwAAJcAAAAAABQA" +
        @"AJUAAAAAABUAAFsAAAAACgAAAFsAAAABCwAAAAAAAAAADAAAAAAAAAAADQAAADsAAAAADgAAAFwAAAAAOgAAAAAAAAAARwAA" +
        @"AAAAAAAASAAAAFwAAAABOwAAAAAAAAAAPAAAAAAAAAAASwAAAAAAAAAATAAAAAAAAAAATQAAAAAAAAAASgAAAAAAAAAAPQAA" +
        @"AF0AAAAAFgAAAF0AAAABFwAAAAAAAAAAGAAAAAAAAAAAGQAAAAAAAAAAGgAAAF4AAAAANQAAAF4AAAABNgAAAAAAAAAANwAA" +
        @"AAAAAAAAOAAAAF8AAAAAEAAAAGAAAAAAEQAAAGAAAAABEgAAAAAAAAAAEwAAAAAAAAAAFAAAAGEAAAAAMAAAAGEAAAABMgAA" +
        @"AAAAAAAAMQAAAAAAAAAAMwAAAGMAAAAAHgAAAGIAAAAAHAAAAGIAAAABHQAAAAAAAAAAHwAAAGMAAAABQgAAAGQAAAAAKAAA" +
        @"AGQAAAABKQAAAGUAAAAAKgAAAAAAAAAAKwAAAAAAAAAALAAAAAAAAAAALQAAAGUAAAABLgAAAAAAAAAAVAAAAAAAAAAAIgAA" +
        @"AAAAAAAAIwAAAAAAAAAAJgAAAAAAAAAAJAAAAAAAAAAAJQAAABkAAAAAAIAAABcAAAAAAIEAAC4AAAAAAGwAAC4AAAABAHIA" +
        @"AEQAAAAAAG0AAEQAAAABAHMAAEAAAAAAAG8AAEAAAAABAHUAADgAAAAAAG4AADgAAAABAHQAAEMAAAAAAHAAAEMAAAABAHYA" +
        @"ADEAAAAAAHEAADEAAAABAHcAADQAAAAAAAITADQAAAABAAgTADoAAAAAAAIVADoAAAABAAgVAAAAAAAAAAIXAAAAAAAAAAgX" +
        @"ADYAAAAAAAQAADYAAAABAAkAAA==")]
    public static readonly ReadOnlyData<byte> GameSettings;


    // see Defaults/GameStartSettings
    [Base64Literal(0,
        @"AAAAAAK8AgAAAIyGRwAAgD8AAAAAmplZPwAAgD8BGA2PTQAAgD8AAIC/AACAPwAAgD8AAIA/AAAAgD9mZqY/AACAPwEAAQwA" +
        @"AAAAAQAAAAAAAAAAAAAAAAAAAAAAAACAPwAAgL8AAIC/AAAAgD//////AACAvwAAAAAAAAAAgD8AAQABw/WoPgHD9ag+AcP1" +
        @"qD4BMzMzPwAAAAAAAAoAAAABAQE=")]
    public static readonly ReadOnlyData<byte> GameStartSettings;


    // see Defaults/TourItemsSeen
    [Base64Literal(0, @"AAAAAA==")]
    public static readonly ReadOnlyData<byte> TourItemsSeen;
}
